---
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: RedisCluster
metadata:
  name: redis-cluster-alpha
  namespace: default
spec:
  clusterSize: 3
  kubernetesConfig:
    image: registry.cn-hangzhou.aliyuncs.com/leijianzhong/redis:6.2.7
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 500m
        memory: 100Mi
      limits:
        cpu: 2000m
        memory: 2Gi
  redisExporter:
    enabled: true
    image: quay.io/opstree/redis-exporter:1.0
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 2000m
        memory: 2Gi
    env:
      - name: REDIS_EXPORTER_INCL_SYSTEM_METRICS
        value: "true"
  sidecars:
    - name: "redis-agent"
      image: "registry.cn-hangzhou.aliyuncs.com/leijianzhong/redis_agent:1.0.1"
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 2000m
          memory: 2Gi
      env:
        - name: VAR_NAME
          value: "value1"
  redisLeader:
    redisConfig:
      additionalRedisConfig: redis-external-config
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - redis-cluster-alpha-leader
            topologyKey: "kubernetes.io/hostname"
  redisFollower:
    redisConfig:
      additionalRedisConfig: redis-external-config
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - redis-cluster-alpha-follower
            topologyKey: "kubernetes.io/hostname"
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: ljz-ganesha-nfs
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi